### PR TITLE
fix: authenticationMiddleware config

### PR DESCRIPTION
**Pull request by peturv**
Fixed issue where configuration passed to authenticationMiddleware could not be accessed properly

### CODE REVIEW

**Comment by Robert-W** [comment]
Hi @peturv, this looks good and thanks for adding tests. It looks like we also messed up the authenticationMiddleware on line 119 in `src/server/router.js`, could you apply your fix their as well?

**Comment by peturv** [comment]
> Hi @peturv, this looks good and thanks for adding tests. It looks like we also messed up the authenticationMiddleware on line 119 in `src/server/router.js`, could you apply your fix their as well?

No problems. 

Missed that call, think those two should be it though. 
(did a free-text search for references to authenticationMiddleware before committing this time).

**Comment by Robert-W** [comment]
Yea same here, that's the only other one I saw. thanks. Ill merge this once the CI is done!!

**Comment by Robert-W** [comment]
Im getting the rest of the PR's done today as well, so I'm hoping to deploy an update later this afternoon

**Pull request merged**
