### PR TITLE
check for scopes that are already an array

### PR DESCRIPTION
**Pull request by 7opf**
When using a customScopeKey, it's possible the scopes are already in an array. If so, return the array as is.

### CODE REVIEW

**Comment by zeevosec** [comment]
Thanks. Looking at this!

**Comment by zeevosec** [comment]
@7opf Please double check your trailing white space changes to `src/server/middleware/sof-scope.middleware.js`. There seems to be linting issues.

**Comment by zeevosec** [comment]
@7opf Still one other error. You can run `yarn lint` to see any.

**Comment by 7opf** [comment]
@zeevosec didn't get any lint errors here, only JSdoc warning which is fixed now

**Pull request merged**
