### PR TITLE
fixed not work enableBaseRoute(router.js): syntax error

### PR DESCRIPTION
**Pull request by dreamofsnail**
fixed syntax error: export module, for init ...

### CODE REVIEW

**Comment by luan-dev** [comment]
Hey @dreamofsnail 

Could you get the checks to run?

**Comment by dreamofsnail** [comment]
> Hey @dreamofsnail
> 
> Could you get the checks to run?

Sure, I was check 'node-fhir-server-mongo'.

* Original code: 'for' loop passing and 'routes' reference miss
image

* Apply modify Code
image

**Comment by luan-dev** [comment]
Sorry for the confusion, could you get the GitHub Action check to run? This should be a setting on your repo (you may need to manually trigger it too)

image

**Comment by dreamofsnail** [comment]
Sorry. I don't have any experience... ('Actions'..)
(I discovered the problem by accident during testing and wanted to pass it on.)
I will cancel this PR.
But I think it would be good to solve the problem.
good luck! :)

**Pull request closed without merging**
