### PR TITLE
Add @hapi/bourne for prototype injection security

### PR DESCRIPTION
**Pull request by dominathan**
Prevents malicious payloads with __proto__ property and returns forbidden OperationOutcome

### CODE REVIEW

**Comment by dominathan** [comment]
I'm back baby

**Comment by dominathan** [comment]
@Robert-W @jonterrylee don't leave me like that.  I thought we were friends.

**Comment by Robert-W** [comment]
Hey man, been a while. Sorry for the delays, looks good to me as well so we'll get a new release published soon.

**Comment by Robert-W** [comment]
Also, Meet Shane (@zeevosec), he's new to the FHIR team as of shortly after Seattle. You will probably see him contributing here and doing pr's from time to time

**Comment by dominathan** [comment]
Glad to meet you all.  Happy to help out when I can

**Pull request merged**
