### PR TITLE
Feature: Custom Error Implementation

### PR DESCRIPTION
**Pull request by dominathan**
A user can now reject errors in his/her implementation that are custom.  By toggling
`error.isCustom = true`, a user will need to set `statusCode`, `code`, `severity`, and `message`.

I had to change all controller actions from 
`next(errors.internal(err.message, base_version));` to 
`next(errors.internal(err, base_version));` passing the entire error object.  

The only real changes are at the very bottom... server/server.js, server/utils/error.utils.js, and server/utils/error.utils.test.js

Changed `internal` error test to show it in action

My implementation for generating a 404 error looks like so
`custom-error.js`
```js
const logger = require('./logger')

class ErrorNotFound extends Error {
  constructor(...params) {
    super(...params)

    if(Error.captureStackTrace) {
      Error.captureStackTrace(this,ErrorNotFound)
    }

    this.statusCode = 404
    this.severity = 'warning'
    this.code = 'not-found'
    this.isCustom = true

    logger.warn('Resource not found.')
  }
}

module.exports = ErrorNotFound
```

and `medication.js` searchById

```js
module.exports.searchById = (args, context, logger) => {
	logger.info(`Getting medication with ID: ${args.id}`)
	return new Promise(async (resolve, reject) => {
		try {
			let data = await getDispensableDrugById(args.id)
			if (data.statusCode === 404) {
				const notFound = new ErrorNotFound('Resource not found.')
				return reject(notFound)
			}
			
			const resp = JSON.parse(data.body)
			const convertedFhirMed = fhirMedicationObject(resp.DispensableDrug)
			resolve(convertedFhirMed)
		} catch (err) {
			reject(err)
		}
	})
```

### CODE REVIEW

**Comment by dominathan** [comment]
#153

**Comment by jonterrylee** [comment]
Thanks!!  We'll take a look first thing in the morning

**Comment by dominathan** [comment]
Fixing something.  Don't merge.

**Comment by dominathan** [comment]
Alright, the problem for me was making it do custom logging because we had `logger.err(err)` for every controller catch.  I pulled that out and moved it to the logger.

**Comment by jonterrylee** [comment]
Thanks @dominathan 

Is this ready to be looked at?  We're going to validate this with the 2.0 branch and get it ready for release.

**Comment by dominathan** [comment]
Yes, I am using it on my fork.

**Comment by Robert-W** [comment]
Hey @dominathan, thanks again for putting this together. Sorry for being MIA for a while, Jon and I have been heads down designing some infrastructure for an enterprise version we hope to demo or at least have ready for dev days at Microsoft this summer.

As Jon was saying, we are also preparing 2.0 (which supports R4 with newly generated resources that fixes several issues !!!). With 2.0 there will be some breaking changes and when I finally got to look into this, I realized that 2.0 already supports this capability out of the box and has made several of the same enhancements.

Just to list a few real quickly:

- error utils will be removed from all controllers, potentially even completely removed for a mechanism I hope will be easier (see below)
- controllers are much simpler and are now pass throughs (this creates the biggest breaking change). For example,
```javascript
/**
 * @function search
 * @param {Function} service
 * @return Promise
 */
module.exports.search = function search(service) {
	return (req, res, next) => {
		return service
			.search(req.sanitized_args, { req })
			.then(bundle => handler.read(req, res, bundle))
			.catch(next);
	};
};
```
- Our `handler.read` is now published in [phx-tools](https://github.com/Asymmetrik/phx-tools) and no longer casts any resources. It just sets the response headers.
- Logger is removed from controller arguments, it will need to be required in the future
- Errors can be passed straight through with a status code as long as they are operation outcomes


So for handling errors in 2.0, the idea was something like this (this is a mock for a fully functional controller in a test app and encapsulates pretty much all the breaking changes):
```javascript
const { resolveSchema, loggers } = require('@asymmetrik/node-fhir-server-core');
// Get the default logger, we are using Winston's container API so user's can add their
// own custom loggers with their own transports and everything
const logger = loggers.get('default');

module.exports.searchById = (args, context) => {
	// Get Constructors for these classes
	let OperationOutcome = require(resolveSchema(args.base_version, 'operationoutcome'));
	let Patient = require(resolveSchema(args.base_version, 'patient'));

	return new Promise((resolve, reject) => {
		// Some made up service
		let results = getPatientForArgs(args);
		if (results) {
			// Before, we send results back, now, we cast as Patient in the service
			resolve(new Patient(results));	
		} else {
			// If you send an operation outcome back with a statusCode, it is used for the
			// http status code, otherwise, 500 is used, but now you can create custom
			// operation outcomes
			reject(new OperationOutcome({
				statusCode: 404,
				issue: [{
					severity: 'error',
					code: 'not-found'
				}]
			}));
		}
	});
};
```

With 2.0, my goal was to try to remove some restrictions and give the users more capabilities, but this also means more responsibility, such as casting operation outcomes, patients, bundles, etc.

Since you are a contributor, I would love your feedback on the approach we were thinking of for version 2.0 and could you let us know if this would be a worthwhile upgrade or more hassle than it is worth.

**Comment by dominathan** [comment]
Interesting idea.  I like the more control for sure.  

Like anyone, I'm wary of upgrades.  How much time are you spending upgrade 1.0 implementations to 2.0?  I think if it's the only way to get access to r4 then we won't really have a choice.

**Comment by Robert-W** [comment]
Yea I understand, one of the things I wanted to make sure of was there were minimal breaking changes and that all of them are fixable in the services.

For our test app(we do plan to upgrade our mongo example to 2.0 when available), the changes were minimal. The logger was a require, and instead or returning JSON, we required the resource, a bundle, and an operation outcome, then cast them before returning. So that second code snippet you saw above was all that we had to upgrade, nothing else changes. If your app serves one or two resources, then it would take all of 5 - 10 minutes. If your app supports all resources across all versions, it would take much longer, unless automated :).

However as a side note, I definitely don't want to force anyone to upgrade and there is nothing in the resources themselves that is not backwards compatible, so we will definitely add a task to back port R4 in to the current version. What we could do, which is similar to what other larger projects are doing, is to create a `release/1.3.1` branch and keep those maintained, so we can keep publishing 1.3.2, 1.3.3, and so on without managing tags, and deploy the latest(2.0) from the master branch in parallel. That way if people don't want to upgrade but also want newer features that's fine.

**Comment by dominathan** [comment]
All of this sounds good.

**Comment by Robert-W** [comment]
Ok great, So I'll update our sprint planning to include some of these updates:

- Deploy R4 resources to current version
- Get this merged so their is some support for custom errors in current version
- Starting with the next release, we will create the release/<version> branches so they can be easily supported

**Pull request merged**
