### PR TITLE
Feature Request to $expand value-set by id

### PR DESCRIPTION
**Pull request by dominathan**
https://www.hl7.org/fhir/valueset-operations.html#expand

This is the initial attempt at get $expand running within your code-base.  I am able to return a result using this branch at this route `http://localhost:3001/3_0_1/ValueSet/301/$expand?filter=horse` that looks like the attached

screen shot 2018-10-19 at 3 17 46 pm

Let me know if this matches what you are thinking and changes that need to be made.

### CODE REVIEW

**Comment by dominathan** [comment]
Checking in again to see your thoughts on the direction of this feature @jonterrylee

**Comment by jonterrylee** [comment]
Hey @dominathan 

Sorry I was out of town for the last week and just got back.  We'll go over this with the team today.  

I can't thank you enough for your contribution.  Greatly appreciated!

**Comment by jonterrylee** [comment]
@dominathan We just noticed that you had a gitignore for prettier.  How do you like it so far?  It was one of our tasks to include to this repo.

If you don't mind, are you willing to include the prettierrc in a PR?

**Comment by dominathan** [comment]
Sure, I love prettier.  Not having to think about formatting with a bunch of developers is a dream.

**Pull request merged**
