### PR TITLE
Upgrade jwk-to-pem to address timing attack

### LINKED ISSUE #215: Elliptic Timing Attack
### Do you want to request a feature, report a bug, or improve documentation?
Reporting a security defect.

Hello, Linux Community Bridge is reporting a Timing Attack based on the `elliptic` library, which is included in `node-fhir-server-core` based on the `jwk-to-pem` library which uses it as a dependency. 

Screen Shot 2019-12-04 at 12 42 03 PM

I've confirmed that its' `jwk-to-pem` pulling in [elliptic:^6.2.3](https://github.com/Brightspace/node-jwk-to-pem/blob/master/package.json#L35), and have reported the issue to them in brightspace/node-jwk-to-pem#33

Possible resolutions include removing `jwk-to-pem` from `node-fhir-server-core`, or working with Brightspace to get their library patched and then updating the FHIR Server.

### PR DESCRIPTION
**Pull request by j3parker**
Fixes #215

### CODE REVIEW

**Comment by j3parker** [comment]
Our release notes are here: https://github.com/Brightspace/node-jwk-to-pem/releases

You should probably investigate the 2.0 bump:

> * [MAJOR] All PEM output is now in PKCS#8 format

Here is the full diff between 1.2.6 and 2.0.2: https://github.com/Brightspace/node-jwk-to-pem/compare/v1.2.6...master

**Comment by awatson1978** [comment]
@j3parker - Thank you so much for the pull request!  

When this PR is merged in, I'll update the downstream [node-on-fhir](https://github.com/symptomatic/node-on-fhir) repository accordingly.

**Comment by awatson1978** [comment]
Quick question:  What's the timeframe for this being published to NPM?

**Comment by zeevosec** [comment]
I can today and will ping you @awatson1978

**Comment by zeevosec** [comment]
New version **2.0.7** published @awatson1978

**Pull request merged**
