### PR TITLE
feat: some improvements in bundle batch

### PR DESCRIPTION
**Pull request by sychus**
- Add bundle batch routes
- add bundle transaction methods (WIP)

### CODE REVIEW

**Comment by zeevosec** [comment]
Hi

It seems like some tests are still failing here.

**Comment by sychus** [comment]
I already solved the failures in the tests. 
Thank you  @zeevosec

**Comment by jjosef** [comment]
Any chance this can get up to date with master and merged please? Would really like to use the batch/transaction endpoints

**Comment by zeevosec** [comment]
@jjosef Sure I can look at this today. Appreciate the mention as this got lost for me.

**Comment by sychus** [comment]
> @jjosef Sure I can look at this today. Appreciate the mention as this got lost for me.



> @jjosef Sure I can look at this today. Appreciate the mention as this got lost for me.

Hi @zeevosec let me know if you need help with this! Cheers

**Pull request merged**
