### PR TITLE
feat(controllers): Add CatalogEntry controller

### PR DESCRIPTION
**Pull request by michelekorell**
Hello, according to FHIR R4 definition there is a CatalogEntry resource. We found there isn't a controller for this resource in actual revision. (http://hl7.org/fhir/catalogentry.html) We created this controller to be able to use this resource.

### CODE REVIEW

**Comment by zeevosec** [comment]
Hi @michelekorell 

I have been super busy lately so apologies for the delayed response. Is it possible to also add a CatalogEntry parameters file and CatalogEntry class file like the other resources in the `4_0_0` directory?

**Comment by michelekorell** [comment]
Hello, no problem, I was also busy. I go to look with my team to do this improvement.

**Comment by Mooooq** [comment]
Hello, 

I just added the catalogentry parameters configuration. 
As indicated by the fhir specification, only the default settings can be used for catalogentry resource, that is why an empty object is exported.

As for the class, I saw that it was already implemented.

**Comment by zeevosec** [comment]
Hi @Mooooq @michelekorell 

The parameters file needs to export search arguments for CatalogEntry. They can be found here https://www.hl7.org/fhir/catalogentry.html towards the bottom.

**Comment by luan-dev** [comment]
Closing stale PR. Please let me know if this is still active

**Pull request closed without merging**
